apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployments
  labels:
     app: myapp
     tier: frontend
spec:
    template:
      metadata:
         name: nginx-2
         labels:
           app: myapp
      spec:
        containers:
          - name: nginx
            image: nginx
    replicas: 3
    selector:
      matchLabels:
        app: myapp